### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by willirath** [willirath/talk_disentangling_scientific_software#2]
- [x] Finish binderization
  - [x] Ensure binder link is working and loads a JupyterLab
  - [x] Ensure there's a README notebook that is diplayed initially

- [x] Add homework / ideas for possible further steps
  - implement a physical field, that can be queried and lives on a fourth worker?
  - assess the computational cost of each part per iteration, derive an ideal layout or bring ideas for better layouts under certain conditions (communication bandwidth, ...)
  - use more than one particle group per RNG and define a way of still ensuring reproducibility
  
- [x] link on willirath.github.io
